apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediawiki-pv-volume
  labels:
      type: local
spec:
  storageClassName: auto
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mediawiki"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-pv-claim
  namespace: mediawiki-ns
spec:
  storageClassName: auto
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: auto
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  iopsPerGB: "10"
  fsType: ext4
---
