service_ports_worker_one=["80", "22"]
service_ports_worker_two=["22"]
cluster_version=1.17
node_one_size="t2.micro"
node_two_size="t2.medium"
region="us-east-1"
cluster_name="mediawiki-eks"
user="admin"
password="Ab123456"
